'use strict';

const punctuators = {
  '{':    true,
  '(':    true,
  ')':    true,
  '[':    true,
  ']':    true,
  '.':    true,
  '...':  true,
  ';':    true,
  ',':    true,
  '<':    true,
  '>':    true,
  '<=':   true,
  '>=':   true,
  '==':   true,
  '!=':   true,
  '===':  true,
  '!==':  true,
  '+':    true,
  '-':    true,
  '*':    true,
  '**':   true,
  '%':    true,
  '++':   true,
  '--':   true,
  '<<':   true,
  '>>':   true,
  '>>>':  true,
  '&':    true,
  '|':    true,
  '^':    true,
  '!':    true,
  '~':    true,
  '&&':   true,
  '||':   true,
  '?':    true,
  ':':    true,
  '=':    true,
  '+=':   true,
  '-=':   true,
  '*=':   true,
  '**=':  true,
  '%=':   true,
  '<<=':  true,
  '>>=':  true,
  '>>>=': true,
  '&=':   true,
  '|=':   true,
  '^=':   true,
  '=>':   true,
  '/':    true,
  '/=':   true,
  '}':    true,
};

const keywords = {
  'break':      true,
  'do':         true,
  'in':         true,
  'typeof':     true,
  'case':       true,
  'else':       true,
  'instanceof': true,
  'var':        true,
  'catch':      true,
  'export':     true,
  'new':        true,
  'void':       true,
  'class':      true,
  'extends':    true,
  'return':     true,
  'while':      true,
  'const':      true,
  'finally':    true,
  'super':      true,
  'with':       true,
  'continue':   true,
  'for':        true,
  'switch':     true,
  'yield':      true,
  'debugger':   true,
  'function':   true,
  'this':       true,
  'default':    true,
  'if':         true,
  'throw':      true,
  'delete':     true,
  'import':     true,
  'try':        true,
};

const assignment = {
  '=':   true,
  '*=':  true,
  '/=':  true,
  '%=':  true,
  '+=':  true,
  '-=':  true,
  '<<=': true,
  '>>=': true,
  '>>>=': true,
  '&=':  true,
  '^=':  true,
  '|=':  true,
  '**=': true,
};

const simpleop = {

  '**':         14,
  '*':          14,
  '/':          14,
  '%':          14,

  '+':          13,
  '-':          13,

  '<<':         12,
  '>>':         12,
  '>>>':        12,

  '<':          11,
  '<=':         11,
  '>':          11,
  '>=':         11,
  'in':         11,
  'instanceof': 11,


  '==':         10,
  '!=':         10,
  '===':        10,
  '!==':        10,

  '&':          9,
  '^':          8,
  '|':          7,

  '&&':         6,
  '||':         5,
};

module.exports = {
  simpleop,
  keywords,
  punctuators,
  assignment,
};
