'use strict';

const keywords = {
  'break':      true,
  'do':         true,
  'in':         true,
  'typeof':     true,
  'case':       true,
  'else':       true,
  'instanceof': true,
  'var':        true,
  'let':        true,
  'catch':      true,
  'export':     true,
  'new':        true,
  'void':       true,
  'class':      true,
  'extends':    true,
  'return':     true,
  'while':      true,
  'const':      true,
  'finally':    true,
  'super':      true,
  'with':       true,
  'continue':   true,
  'for':        true,
  'switch':     true,
  'yield':      true,
  'debugger':   true,
  'function':   true,
  'this':       true,
  'default':    true,
  'if':         true,
  'throw':      true,
  'delete':     true,
  'import':     true,
  'try':        true,
};

const assignment = {
  '=':   true,
  '*=':  true,
  '/=':  true,
  '%=':  true,
  '+=':  true,
  '-=':  true,
  '<<=': true,
  '>>=': true,
  '>>>=': true,
  '&=':  true,
  '^=':  true,
  '|=':  true,
  '**=': true,
};

module.exports = {
  keywords,
  assignment,
};
